---
title: "FlatAds"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r customViz, include=FALSE}
# source('scrapgratka.R')

plotGratka <- function(district){
    
    Plot.Interactive <- ggplot(data = gratka.oferty[dzielnica == district & powierzchnia %between% c(50, 80) & cena_m %between% c(5, 10)],
                               aes(x = powierzchnia, y = cena_m, col = rok))  + 
        geom_point_interactive(aes(data_id = link, tooltip = paste0('Lokalizacja: ', lokalizacja, '\n',
                                                                    'CenaM_tys: ', round(cena_m, 3), '\n',
                                                                    'Pow: ', powierzchnia, '\n',
                                                                    'Rok: ', rok, '\n'),
                                   onclick = onclick), size = 6, alpha = .6 ) +
        scale_color_gradient2(midpoint = 1980, low = 'red', high = 'blue', mid = 'orange') + 
        labs(x = 'Powierzchnia [m2]', y = 'Cena za metr [tys PLN]') + 
        xlim(c(50, 80)) + ylim(c(5,10.5)) +
        theme_bw()+
        theme(legend.position = 'bottom', legend.title = element_blank(), 
              text = element_text(size = 20), title = element_text(size = 24))+
        guides(colour = guide_colourbar(barwidth = 18))
    
    ggiraph(code = print(Plot.Interactive),
            hover_css = "fill-opacity:.3;cursor:pointer;", zoom_max = 7, width_svg = 15, height_svg = 12)
}

plotOtodom <- function(district){
    shp <- c('21', '23')
    names(shp) <- c('Agencyjna', 'Prywatna')
    Plot.Interactive <- ggplot(data = otodom.oferty[dzielnica == district & powierzchnia %between% c(50, 80) & cena_m %between% c(5, 10)],
                               aes(x = powierzchnia, y = cena_m, col = rok, shape = typOferty))  + 
        geom_point_interactive(aes(data_id = link, tooltip = paste0('Lokalizacja: ', lokalizacja, '\n',
                                                                    'CenaM_tys: ', round(cena_m, 3), '\n',
                                                                    'Pow: ', powierzchnia, '\n',
                                                                    'Rok: ', rok, '\n',
                                                                    'TypOferty: ', typOferty),
                                   onclick = onclick), size = 6, alpha = .6 ) +
        scale_color_gradient2(midpoint = 1980, low = 'red', high = 'blue', mid = 'orange') + 
        scale_size_manual(values = shp) +
        labs(x = 'Powierzchnia [m2]', y = 'Cena za metr [tys PLN]') + 
        xlim(c(50, 80)) + ylim(c(5,10.5)) +
        theme_bw()+
        theme(legend.position = 'bottom', legend.title = element_blank(), 
              text = element_text(size = 20), title = element_text(size = 24))+
        guides(colour = guide_colourbar(barwidth = 18), size = guide_legend())
    
    ggiraph(code = print(Plot.Interactive),
            hover_css = "fill-opacity:.3;cursor:pointer;", zoom_max = 7, width_svg = 15, height_svg = 12)
}

plotNew <- function(){
    Imp.New[, cena_m := powierzchnia/cena]
    shp <- c('21', '23')
    names(shp) <- c('Otodom', 'Gratka')
    Plot.Interactive <- ggplot(data = Imp.New[powierzchnia %between% c(50, 80) & cena_m %between% c(5, 10)],
                               aes(x = powierzchnia, y = cena_m, col = rok, shape = zrodlo))  + 
        geom_point_interactive(aes(data_id = link, tooltip = paste0('Lokalizacja: ', lokalizacja, '\n',
                                                                    'CenaM_tys: ', round(cena_m, 3), '\n',
                                                                    'Pow: ', powierzchnia, '\n',
                                                                    'Rok: ', rok, '\n',
                                                                    'TypOferty: ', typOferty),
                                   onclick = onclick), size = 6, alpha = .6 ) +
        scale_color_gradient2(midpoint = 1980, low = 'red', high = 'blue', mid = 'orange') + 
        scale_size_manual(values = shp) +
        labs(x = 'Powierzchnia [m2]', y = 'Cena za metr [tys PLN]') + 
        xlim(c(50, 80)) + ylim(c(5,10.5)) +
        theme_bw()+
        theme(legend.position = 'bottom', legend.title = element_blank(), 
              text = element_text(size = 20), title = element_text(size = 24))+
        guides(colour = guide_colourbar(barwidth = 18), size = guide_legend())
    
    ggiraph(code = print(Plot.Interactive),
            hover_css = "fill-opacity:.3;cursor:pointer;", zoom_max = 7, width_svg = 15, height_svg = 12)
}

```


Ursynow
=======================================================================


Row
-----------------------------------------------------------------------

### Gratka

```{r Ursynow - Gratka, echo=FALSE}

plotGratka('Ursynow')

```

### OtoDom

```{r Ursynow - otodom, echo=FALSE}

plotOtodom('Ursynow')

```


Sluzew
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Sluzew

```{r Gratka - Sluzew, echo=FALSE}

plotGratka('Sluzew')

```

### OtoDom

```{r Sluzew - otodom, echo=FALSE}

plotOtodom('Sluzew')

```


Mokotow
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Mokotow

```{r Mokotow - Gratka, echo=FALSE}

plotGratka('Mokotow')

```

### OtoDom

```{r Mokotow - otodom, echo=FALSE}

plotOtodom('Mokotow')

```


Muranow
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Muranow

```{r Muranow - Gratka, echo=FALSE}

plotGratka('Muranow')

```

### OtoDom

```{r Muranow - otodom, echo=FALSE}

plotOtodom('Muranow')

```


Wola
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Wola

```{r Wola - Gratka, echo=FALSE}

plotGratka('Wola')

```

### OtoDom

```{r Wola - otodom, echo=FALSE}

plotOtodom('Wola')

```


Ochota
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Ochota

```{r Ochota - Gratka, echo=FALSE}

plotGratka('Ochota')

```

### OtoDom

```{r Ochota - otodom, echo=FALSE}

plotOtodom('Ochota')

```


Bielany
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Bielany

```{r Bielany - Gratka, echo=FALSE}

plotGratka('Bielany')

```

### OtoDom

```{r Bielany - otodom, echo=FALSE}

plotOtodom('Bielany')

```


Zoliborz
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Zoliborz

```{r Zoliborz, echo=FALSE}

plotGratka('Zoliborz')

```

### OtoDom

```{r Zoliborz - otodom, echo=FALSE}

plotOtodom('Zoliborz')

```


Nowe
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Nowe ogloszenia

```{r Nowe, echo=FALSE}

if (nrow(Imp.New) > 0){plotNew()}


```